name: Build and deploy documentation site to GitHub Pages based on repo contents

on: workflow_dispatch

#on:
#  push:
#    branches:
#      - release
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository:  simplesamlphp/simplesamlphp.github.io 
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - run: pip install markdown
    - run: pip install glob2
    - run: pip install urllib3
    - run: pip install beautifulsoup4
    - run: ls ./_site/
    - run: ls ./_site/docs/
    - name: execute py script # run the run.py to get the latest data
      run: |
         python website_scripts/mk_docs.py
    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository:  simplesamlphp/simplesamlphp.github.io 
